import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Providers } from "@/components/Providers";

// Import fonts via next/font/google
import { Playfair_Display } from "next/font/google";
import { Dancing_Script } from "next/font/google";

// Setup fonts with proper fallback
const playfair = Playfair_Display({ subsets: ["latin"], display: "swap" });
const dancingScript = Dancing_Script({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen antialiased", playfair.className)}>
        <Providers>
          <main className="h-screen dark text-foreground bg-background ">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
