import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Providers } from "@/components/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Krona+One&family=Raleway:ital,wght@0,100..900;1,100..900&display=swap"
        />
      </head>
      <body className={cn("min-h-screen antialiased font-[Playfair]")}>
        <Providers>
          <main className="h-screen dark text-foreground bg-background ">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
